name: sample-workflow
on:
  push:
    branches: [master]

jobs:
  job1:
    runs-on: ubuntu-latest
    staps:
    -name: checks-out your repository under $GITHUB_WORKSPACE
      uses: actions/checout@v2
    -name: use echo command
      uses: echo "sample-workflow"
