name: sample-workflow
on:
  schedule:
    # UTC の 02:00 は JST だと 11:00 。
    - cron: '30 0 * * *'
  push:
    branches: [develop]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checks-out your repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
      - name: use echo command
        run: echo "sample-workflow"
